markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
baseurl: /
exclude: ['node_modules', 'blueprint.md', '*.sublime-*']
gems:
  - jekyll-sitemap
